### ISSUE TITLE
Error when using SVGGroup in FXML

### ISSUE THREAD

**Issue by frnusmartobjects** [Xyanid/svgFX#12]
When using SVGGroup in FXML

```fxml
<SVGGroup fx:id="my_svg_illustration" />
```

 I'm having the following error:

```
Unable to coerce de.saxsys.svgfx.core.elements.SVGGroup to javafx.scene.Node
Unable to instantiate
```

And when running the program I am getting 

```
Caused by: java.lang.InstantiationException: de.saxsys.svgfx.core.elements.SVGGroup
	at java.lang.Class.newInstance(Class.java:427)
	at sun.reflect.misc.ReflectUtil.newInstance(ReflectUtil.java:51)
	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1009)
	... 21 more
Caused by: java.lang.NoSuchMethodException: de.saxsys.svgfx.core.elements.SVGGroup.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 23 more
```

**Comment by Xyanid** [comment]
Can you provide me with the svg that you wanted to load?

**Comment by Xyanid** [comment]
I just see that you are using `SVGGroup` directly from svgFX, which is not how it is intended to be used.
Though I just saw that the wiki states it to be used like this, which is infact incorrect. --> I will fix the wiki.

To clarify:
- If you want to load svgs only using svgFX, you would need to implement your own control which uses the `SVGParser`. 
- You can use svgFX by using styleableFX, which provides the correct `SVGGroup` element that can be used in FXML
-- path would be `de.saxsys.styleablefx.controls.SVGGroup`
-- see https://github.com/Xyanid/styleableFX

**Comment by Xyanid** [comment]
I updated the wiki to link to the wiki of styleableFX when wanting to directly load svg files. Let me know if that works for you now.

**Comment by frnusmartobjects** [comment]
Thank you. Yes, now it is compiling and loading the SVG, although I see two problems. First the displayed SVG isn't the same as the SVg I see in my browser. Secondly, is it possible to change the SVG in runtime?

**Comment by Xyanid** [comment]
Can you provide the svg so I can check what the issue is? 

As for changing it at runtime, if you are familiar with how javaFx does the [styling](https://docs.oracle.com/javafx/2/api/javafx/scene/doc-files/cssref.html#introscenegraph) via css, you can go that way.

e.g you could define different styles, and then define a what svg is loaded based on the style like this
```
#svgGroup {
  -saxsys-svg-url: "svg/maximize.svg";
}

#svgGroup:selected {
  -saxsys-svg-url: "svg/minimize.svg";
}
```

**Comment by frnusmartobjects** [comment]
Sure, is there a way to send it to you privately?

**Comment by frnusmartobjects** [comment]
@Xyanid How can I send you the SVG file?

**Comment by Xyanid** [comment]
you could send them to xyanid@web.de, that would be one way.
